# Generated by Django 5.0.6 on 2024-06-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='determining_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='determined_by', to='variables.variable'),
        ),
    ]
