# Generated by Django 4.2.13 on 2024-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0004_alter_yearlyinputvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyinputvalue',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyinputvalue',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
