# Generated by Django 4.2.13 on 2024-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0005_alter_yearlyinputvalue_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='constant',
            new_name='base_exp',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='multiplier',
            new_name='base_log',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='standard_deviation_of_multiplier',
            new_name='constant_term',
        ),
        migrations.AddField(
            model_name='variable',
            name='cubic_coeff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='interpolation_method',
            field=models.CharField(choices=[('Linear', 'Linear'), ('Spline', 'Spline'), ('Polynomial', 'Polynomial'), ('Newton', 'Newton')], default='Linear', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='linear_coeff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='quadratic_coeff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='standard_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
