# Generated by Django 4.2.13 on 2024-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0006_rename_constant_variable_base_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='interpolation_method',
            field=models.CharField(blank=True, choices=[('Linear', 'Linear'), ('Spline', 'Spline'), ('Polynomial', 'Polynomial'), ('Newton', 'Newton')], max_length=10, null=True),
        ),
    ]
