# Generated by Django 4.2.13 on 2024-07-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0008_remove_variable_interpolation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='level_in_2023',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
