# Generated by Django 4.2.13 on 2024-07-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0009_alter_variable_level_in_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='base_exp',
            new_name='exp_coeff',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='base_log',
            new_name='exp_rate_coeff',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='constant_term',
            new_name='log_coeff',
        ),
    ]
